# Development Configuration
server:
  pocketbaseHost: "127.0.0.1"
  
  pocketbasePort: "8090"
  # URL of the frontend application. Used for generating absolute URLs in emails, etc.
  appUrl: "http://localhost:5173"
  # Directory where PocketBase will store its data, including the SQLite database and files.
  dataDir: "pb_data"

log:
  # Logging level (e.g., "debug", "info", "warn", "error").
  level: "debug"

  # Log output format ("text" or "json").
  format: "text"

  # Whether to include the source code location (file and line number) in the log output.
  addSource: false